In [2]:
import numpy as np

In [52]:
data = np.random.randint(100, 130, size=(8, 8))
data

array([[102, 122, 115, 115, 100, 115, 123, 102],
       [110, 115, 117, 126, 129, 124, 105, 119],
       [102, 129, 116, 125, 106, 105, 128, 122],
       [112, 124, 102, 106, 107, 100, 104, 128],
       [128, 112, 112, 104, 128, 101, 121, 114],
       [119, 100, 110, 129, 112, 122, 109, 112],
       [128, 119, 124, 106, 109, 120, 109, 126],
       [101, 110, 111, 122, 111, 113, 127, 112]])

In [53]:
num_three = data % 3 == 0
num_five = data % 5 == 0
num_fif = data % 15 == 0

In [54]:
result = data.astype("str")
result

array([['102', '122', '115', '115', '100', '115', '123', '102'],
       ['110', '115', '117', '126', '129', '124', '105', '119'],
       ['102', '129', '116', '125', '106', '105', '128', '122'],
       ['112', '124', '102', '106', '107', '100', '104', '128'],
       ['128', '112', '112', '104', '128', '101', '121', '114'],
       ['119', '100', '110', '129', '112', '122', '109', '112'],
       ['128', '119', '124', '106', '109', '120', '109', '126'],
       ['101', '110', '111', '122', '111', '113', '127', '112']],
      dtype='<U11')

In [55]:
result[num_three] = "fiz"
result[num_five] = "buz"
result[num_fif] = "fbz"

In [56]:
result

array([['fiz', '122', 'buz', 'buz', 'buz', 'buz', 'fiz', 'fiz'],
       ['buz', 'buz', 'fiz', 'fiz', 'fiz', '124', 'fbz', '119'],
       ['fiz', 'fiz', '116', 'buz', '106', 'fbz', '128', '122'],
       ['112', '124', 'fiz', '106', '107', 'buz', '104', '128'],
       ['128', '112', '112', '104', '128', '101', '121', 'fiz'],
       ['119', 'buz', 'buz', 'fiz', '112', '122', '109', '112'],
       ['128', '119', '124', '106', '109', 'fbz', '109', 'fiz'],
       ['101', 'buz', 'fiz', '122', 'fiz', '113', '127', '112']],
      dtype='<U11')

In [62]:
data = np.random.randint(1, 20, size=(5, 5))
data

array([[19, 18,  4,  4,  6],
       [ 7, 19,  1, 17,  1],
       [ 5,  2,  7,  7,  2],
       [17, 18,  7,  5,  1],
       [ 8, 11, 15, 17,  5]])

In [63]:
high = np.max(data)
low = np.min(data)

In [67]:
max_high = data == high
min_low = data == low

In [68]:
result = data.astype("str")
result

array([['19', '18', '4', '4', '6'],
       ['7', '19', '1', '17', '1'],
       ['5', '2', '7', '7', '2'],
       ['17', '18', '7', '5', '1'],
       ['8', '11', '15', '17', '5']], dtype='<U11')

In [71]:
result[max_high] = "MAX"
result[min_low] = "MIN"
result

array([['MAX', '18', '4', '4', '6'],
       ['7', 'MAX', 'MIN', '17', 'MIN'],
       ['5', '2', '7', '7', '2'],
       ['17', '18', '7', '5', 'MIN'],
       ['8', '11', '15', '17', '5']], dtype='<U11')

In [78]:
np.logspace(3, 6, 3)

array([   1000.        ,   31622.77660168, 1000000.        ])

In [4]:
df_race = pd.read_csv("datas/2014_p.csv", encoding="euc-kr")
df_race.tail(2)

ID RCTRCK     RACE_DE  RACE_NO  PARTCPT_NO  RANK RCHOSE_NM HRSMN  \
27216  27217     제주  2014-11-29        9           7   6.0      미주여행   김경휴   
27217  27218     제주  2014-11-29        9           6   1.0       철옹성   장우성   

           RCORD ARVL_DFFRNC EACH_SCTN_PASAGE_RANK  A_WIN_SYTM_EXPECT_ALOT  \
27216  0:01:31.1          13   2 -  -  - 2 - 3 - 6                     6.2   
27217  0:01:26.6         NaN   1 -  -  - 1 - 1 - 1                     3.9   

       WIN_STA_EXPECT_ALOT  
27216                  9.4  
27217                  2.9

In [5]:
df_horse = pd.read_csv("datas/2014_s.csv", encoding="euc-kr")
df_horse.tail(2)

ID RCTRCK     RACE_DE PRDCTN_NATION_NM SEX  AGE  BND_WT TRNER  \
27216  27217     제주  2014-11-29                한   거  NaN    53.0   강대은   
27217  27218     제주  2014-11-29                한   거  NaN    57.5   박병진   

      RCHOSE_OWNR_NM  RCHOSE_BDWGH  
27216            김기준           281  
27217            강상우           314

In [6]:
df_merged = pd.merge(df_race, df_horse)
df_merged.tail(2)

ID RCTRCK     RACE_DE  RACE_NO  PARTCPT_NO  RANK RCHOSE_NM HRSMN  \
27216  27217     제주  2014-11-29        9           7   6.0      미주여행   김경휴   
27217  27218     제주  2014-11-29        9           6   1.0       철옹성   장우성   

           RCORD ARVL_DFFRNC EACH_SCTN_PASAGE_RANK  A_WIN_SYTM_EXPECT_ALOT  \
27216  0:01:31.1          13   2 -  -  - 2 - 3 - 6                     6.2   
27217  0:01:26.6         NaN   1 -  -  - 1 - 1 - 1                     3.9   

       WIN_STA_EXPECT_ALOT PRDCTN_NATION_NM SEX  AGE  BND_WT TRNER  \
27216                  9.4                한   거  NaN    53.0   강대은   
27217                  2.9                한   거  NaN    57.5   박병진   

      RCHOSE_OWNR_NM  RCHOSE_BDWGH  
27216            김기준           281  
27217            강상우           314

In [9]:
df_merged["COUNT"] = 1
df_merged.tail(2)

ID RCTRCK     RACE_DE  RACE_NO  PARTCPT_NO  RANK RCHOSE_NM HRSMN  \
27216  27217     제주  2014-11-29        9           7   6.0      미주여행   김경휴   
27217  27218     제주  2014-11-29        9           6   1.0       철옹성   장우성   

           RCORD ARVL_DFFRNC  ... A_WIN_SYTM_EXPECT_ALOT  WIN_STA_EXPECT_ALOT  \
27216  0:01:31.1          13  ...                    6.2                  9.4   
27217  0:01:26.6         NaN  ...                    3.9                  2.9   

       PRDCTN_NATION_NM SEX AGE  BND_WT  TRNER RCHOSE_OWNR_NM RCHOSE_BDWGH  \
27216                 한   거 NaN    53.0    강대은            김기준          281   
27217                 한   거 NaN    57.5    박병진            강상우          314   

       COUNT  
27216      1  
27217      1  

[2 rows x 21 columns]

In [13]:
df = df_merged.pivot_table("COUNT", "RANK", "SEX", aggfunc=np.sum)
df.head(5)

SEX       거       수       암
RANK                       
1.0   528.0  1067.0   964.0
2.0   488.0  1033.0  1021.0
3.0   538.0   984.0  1029.0
4.0   524.0   947.0  1082.0
5.0   502.0   897.0  1148.0

In [15]:
count = df_merged.groupby("SEX").size()
count

SEX
거     5576
수     9869
암    11773
dtype: int64

In [16]:
result = df / count * 100
result.head()

SEX          거          수         암
RANK                               
1.0   9.469154  10.811632  8.188227
2.0   8.751793  10.467119  8.672386
3.0   9.648494   9.970615  8.740338
4.0   9.397418   9.595704  9.190521
5.0   9.002869   9.089067  9.751125

In [18]:
result = round(result, 2)
result.head()

SEX      거      수     암
RANK                   
1.0   9.47  10.81  8.19
2.0   8.75  10.47  8.67
3.0   9.65   9.97  8.74
4.0   9.40   9.60  9.19
5.0   9.00   9.09  9.75

In [19]:
df_merged["POINTS"] = df_merged["RANK"].apply(
    lambda rank: 4 - rank if rank <= 3 else 0)

In [20]:
df = df_merged.groupby("RCHOSE_NM").agg("sum").reset_index()

In [22]:
df = df.sort_values("POINTS", ascending=False)[["RCHOSE_NM", "POINTS"]]

In [24]:
result = df.reset_index(drop=True)
result.head()

RCHOSE_NM  POINTS
0      신천보스    25.0
1     금포스카이    24.0
2     한강의기적    23.0
3      가리사니    23.0
4      신천돌채    22.0

In [25]:
import makedata

In [28]:
datas = {}
datas["Users ID"] = list(range(1, 9))
datas["Age"] = [makedata.get_age() for _ in range(8)]
names = []
while True:
    name = makedata.get_name()
    if name not in names:
        names.append(name)
    if len(names) >= 8:
        break
datas["Name"] = names

user_df = pd.DataFrame(datas)
user_df

Users ID  Age     Name
0         1   33    Alvin
1         2   29     Alex
2         3   24   Arnold
3         4   24    Billy
4         5   21   Andrew
5         6   25  Anthony
6         7   33      Jin
7         8   27     Alan